### ISSUE TITLE
Tiny change to take in account gtag.js?

### ISSUE THREAD

**Issue by sneko** [duyet/gaxy#48]
Hi @duyet ,

Thanks for this repo, it's one of the most implemented (docker, helm...)!

I'm getting some troubles to make your proxy working and I would appreciate some help 😄 

I'm using GA4 (Google Analytics 4) and my frontend plugin in Vue.js fetches the Google script from:
`https://www.googletagmanager.com/gtag/js`

I set:
`GOOGLE_ORIGIN: "https://www.googletagmanager.com"`

And used as resource URL `www.mydomain.com/gtag/js`. I saw the script being proxified but inside the URL were not replaced.

From what I see on
https://github.com/duyet/gaxy/blob/42db1406dd667bc98b90e9e958a42024bcb4d50e/server.go#L151-L155 

I think the domain `www.googletagmanager.com` should be added.

I download the proxified script, modified manually and used a:
```
  <script async src="/ana.js?id=XXXXXXX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { window.dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'XXXXXXX', {
      send_page_view: true
    });
  </script>
```

And I'm able to see in realtime the session in GA4. So I guess that's just this tiny change to do.

Could you please redeploy everything for this? Otherwise will manage my own Docker image.

Thank you 😄

**Comment by duyet** [comment]
Hi @sneko,

Thanks for your feedback. I just have added the Google Tag Manager domains. The new image has been released at https://github.com/duyet/gaxy/releases/tag/v0.1.2-beta.2.

Let me know if you have any more concerns :D.
Thanks,

**Comment by sneko** [comment]
@duyet unfortunately it seems there is an additional thing to change that I didn't see on friday (sorry about that).

When taking the script:
```
https://www.googletagmanager.com/gtag/js?id=G-XXX
```
_(use your measurement ID so the script is fully filled)_

You can find the line:
```
var a="www";XA&&WA&&(a=WA);return"https://"+a+".google-analytics.com/g/collect"
```

Which mean when the proxy will replace the domains the frontend will try in all cases to push on:
```
https://www.mysubdomain.mydomain.com/g/collect
```

In my cases I could make some workarounds so I have a certificate for the additional prefix "www" but it sounds weird since the original domain was: `mysubdomain.mydomain.com` (which is used to retrieved the script).

I guess we have to find a regex or a hard replace to have at the end only:
```
var a="www";XA&&WA&&(a=WA);return"https://mysubdomain.mydomain.com/g/collect"
```

(I tried to look at the `WA` variable, but didn't find a way to customize it from the outside, and also since there is the remaining "dot", it's stuck (`https://"+a+".`))

**Comment by sneko** [comment]
To sum up, I succeeded in making it working... I didn't make a PR because I feel it's a bit hacky to "route" the proxy request to the right Google domain with hard conditions.

But in case it can help understanding the issue, I'm replacing all those domains:
```
		find := []string{
			"\"+(a?a+\".\":\"\")+\"analytics.google.com",
			"ssl.google-analytics.com",
			"\"+a+\".google-analytics.com",
			"www.google-analytics.com",
			"google-analytics.com",
			"www.googletagmanager.com",
			"googletagmanager.com",
		}
```
(we are fine until the Google minifier will replace `a` by another variable, but very unlikely since it depends on the function variables number and their order)

And inside `handleRequestAndRedirect()` I just check if that's a "collect" endpoint from Google. If so, it's targeting their GA domain.

```
	// Trim prefix
	reqURI := string(c.Request().RequestURI())
	if config.RoutePrefix != "" && strings.HasPrefix(reqURI, config.RoutePrefix+"/") {
		reqURI = strings.TrimPrefix(reqURI, config.RoutePrefix)
		upstreamReq.SetRequestURI(reqURI)
	}

	// [WORKAROUND] To "easily" manage multiple Google domains, set this hard condition
	var targetOrigin string
	if strings.HasPrefix(reqURI, "/g/collect") {
		targetOrigin = "https://www.google-analytics.com"
	} else {
		targetOrigin = config.GoogleOrigin
	}

	// Overwrite
	url, _ := url.Parse(targetOrigin)
	upstreamReq.SetHost(url.Host)
	upstreamReq.URI().SetScheme(url.Scheme)
```

Once more, I'm not satisfied about this but it will help me moving forward. Curious to know your thoughts @duyet 😃 

_If someone wants to test please use the image `sneko/gaxy:v0.1.2-beta.3` (additional `v` for the version haha sorry)_
